(ns classifier.config.twitter)

;; Hastags taken from http://www.socialbrite.org/2011/12/27/45-hashtags-for-social-change/
(def hashtags [
               "#socialgood"
               "#socialchange"
               "#cause"
               "#causes"
               "#volunteer"
               "#volunteers"
               "#volunteering"
               "#change"
               "#giveback"
               "#dogood"
               "#nonprofit"
               "#nonprofits"
               "#nfp"
               "#notforprofit"
               "#philanthropy"
               "#charity"
               "#charities"
               "#foundation"
               "#foundations"
               "#microfinance"
               "#socialenterprise"
               "#humandrights"
               "#poverty"
               "#hunger"
               "#aim"
               "#diversity"
               "#sustainability"
               "#health"
               "#sdoh"
               "#disabilities"
               "#green"
               "#eco"
               "#environment"
               "#earthtweet"
               "#humantrafficking"
               "#climate"
               "#climatechange"
               "#failtertrade"
               ])
